config/routes.rb
    get  'messages/reports'          => 'messages#reports'
    
    # ADMIN PERSONIFICATIONS
    delete 'personifications'     => 'personifications#destroy', :as => :personification
    post   'personifications/:id' => 'personifications#create',  :as => :personifications
    
    # ADMIN PURCHASES
    resources :purchases, only: %i(index new create edit update)
    get       'purchases/:id/links/form' => 'purchases#link_form'
    post      'purchases/:id/links/send' => 'purchases#send_link'
    
    # ADMIN REPORTS
    delete 'reports/:id/accept'  => 'reports#accept'
    delete 'reports/:id/decline' => 'reports#decline'
    
    # ADMIN SETTINGS
    get    'settings/locations'                    => 'settings#locations'
    post   'settings/locations/create'             => 'settings#create_location'
    put    'settings/locations/:id/update'         => 'settings#update_location'
    get    'settings/school_levels'                => 'settings#school_levels'
    delete 'settings/school_levels/:id/delete'     => 'settings#delete_school_level'
    post   'settings/school_levels/new'            => 'settings#new_school_level'
    get    'settings/subjects'                     => 'settings#subjects'
    delete 'settings/subjects/:id/delete'          => 'settings#delete_subject'
    post   'settings/subjects/new'                 => 'settings#new_subject'
    get    'settings/tags'                         => 'settings#tags'
    delete 'settings/tags/:id/delete'              => 'settings#delete_tag'
    get    'settings/tags/:id/show/lessons'        => 'settings#lessons_for_tag'
    get    'settings/tags/:id/show/media_elements' => 'settings#media_elements_for_tag'
    
    # ADMIN USERS
    get    'users'                => 'users#index',         :as => :users
    get    'users/get_full_names' => 'users#get_full_names'
    delete 'users/:id'            => 'users#destroy'
    get    'users/:id'            => 'users#show',          :as => :user
    put    'users/:id/activate'   => 'users#activate',      :as => :users_activate
    put    'users/:id/ban'        => 'users#ban',           :as => :users_ban
    post   'users/:id/reconfirm'  => 'users#reconfirm',     :as => :send_again_confirmation
    put    'users/:id/set_status' => 'users#set_status'
    
  end
  
  # AUDIO EDITOR
  get  'audios/:audio_id/edit'   => 'audio_editor#edit'
  post 'audios/cache/empty'      => 'audio_editor#empty_cache',   :as => :audio_editor_empty_cache
  get  'audios/cache/restore'    => 'audio_editor#restore_cache', :as => :audio_editor_restore_cache
  post 'audios/cache/save'       => 'audio_editor#save_cache',    :as => :audio_editor_save_cache
  post 'audios/commit/new'       => 'audio_editor#save'
  post 'audios/commit/overwrite' => 'audio_editor#overwrite'
  get  'audios/new'              => 'audio_editor#new'
  
  # DASHBOARD
  get 'dashboard/lessons'        => 'dashboard#lessons',        :as => :dashboard_lessons
  get 'dashboard/media_elements' => 'dashboard#media_elements', :as => :dashboard_media_elements
  
  # DOCUMENTS
  post   'documents'              => 'documents#create',     :as => :documents
  get    'documents/create/fake'  => 'documents#create_fake'
  delete 'documents/:document_id' => 'documents#destroy'
  post   'documents/:document_id' => 'documents#update',     :as => :document
  
  # FAQS
  get 'faqs'                               => 'faqs#index',             :as => :faqs
  get 'faqs/lessons/:num/answer'           => 'faqs#lessons',           :as => :lessons_faqs
  get 'faqs/media_elements/:num/answer'    => 'faqs#media_elements',    :as => :media_elements_faqs
  get 'faqs/profile/:num/answer'           => 'faqs#profile',           :as => :profile_faqs
  get 'faqs/virtual_classroom/:num/answer' => 'faqs#virtual_classroom', :as => :virtual_classroom_faqs
  
  # GALLERIES
  get 'audios/galleries/audio'               => 'galleries#audio_for_audio_editor' # audio in audio editor
  get 'audios/galleries/audio/new_block'     => 'galleries#audio_for_audio_editor_new_block'
  get 'images/galleries/image'               => 'galleries#image_for_image_editor' # image in image editor
  get 'images/galleries/image/new_block'     => 'galleries#image_for_image_editor_new_block'
  get 'lessons/galleries/audio'              => 'galleries#audio_for_lesson_editor' # audio in lesson editor
  get 'lessons/galleries/audio/new_block'    => 'galleries#audio_for_lesson_editor_new_block'
  get 'lessons/galleries/document'           => 'galleries#document_for_lesson_editor' # documents in lesson editor
  get 'lessons/galleries/document/filter'    => 'galleries#document_for_lesson_editor_filter'
  get 'lessons/galleries/document/new_block' => 'galleries#document_for_lesson_editor_new_block'
  get 'lessons/galleries/image'              => 'galleries#image_for_lesson_editor' # image in lesson editor
  get 'lessons/galleries/image/new_block'    => 'galleries#image_for_lesson_editor_new_block'
  get 'lessons/galleries/video'              => 'galleries#video_for_lesson_editor' # video in lesson editor
  get 'lessons/galleries/video/new_block'    => 'galleries#video_for_lesson_editor_new_block'
  get 'videos/galleries'                     => 'galleries#mixed_for_video_editor' # mixed image + video + text in video editor
  get 'videos/galleries/audio'               => 'galleries#audio_for_video_editor' # audio in video editor
  get 'videos/galleries/audio/new_block'     => 'galleries#audio_for_video_editor_new_block'
  get 'videos/galleries/image/new_block'     => 'galleries#mixed_for_video_editor_image_new_block'
  get 'videos/galleries/video/new_block'     => 'galleries#mixed_for_video_editor_video_new_block'
  
  # GALLERIES QUICK UPLOAD
  post 'lessons/galleries/audios'                     => 'galleries#create_audio'
  post 'lessons/galleries/documents'                  => 'galleries#create_document'
  get  'lessons/galleries/documents/create/fake'      => 'galleries#create_fake_document'
  post 'lessons/galleries/images'                     => 'galleries#create_image'
  get  'lessons/galleries/media_elements/create/fake' => 'galleries#create_fake_media_element'
  post 'lessons/galleries/videos'                     => 'galleries#create_video'
  
  # IMAGE EDITOR
  post 'images/add_text'         => 'image_editor#add_text'
  post 'images/commit/new'       => 'image_editor#save'
  post 'images/commit/overwrite' => 'image_editor#overwrite'
  post 'images/crop'             => 'image_editor#crop'
  get  'images/:image_id/edit'   => 'image_editor#edit'
  post 'images/undo'             => 'image_editor#undo'
  
  # LESSON BUTTONS
  post 'lessons/:lesson_id/add'                      => 'lessons#add'
  post 'lessons/:lesson_id/copy'                     => 'lessons#copy'
  post 'lessons/:lesson_id/destroy'                  => 'lessons#destroy'
  post 'lessons/:lesson_id/dislike'                  => 'lessons#dislike'
  post 'lessons/:lesson_id/dont_notify_modification' => 'lessons#dont_notify_modification'
  post 'lessons/:lesson_id/like'                     => 'lessons#like'
  post 'lessons/:lesson_id/notify_modification'      => 'lessons#notify_modification'
  post 'lessons/:lesson_id/publish'                  => 'lessons#publish'
  post 'lessons/:lesson_id/remove'                   => 'lessons#remove'
  post 'lessons/:lesson_id/unpublish'                => 'lessons#unpublish'
  post 'virtual_classroom/:lesson_id/add_lesson'     => 'virtual_classroom#add_lesson'
  post 'virtual_classroom/:lesson_id/remove_lesson'  => 'virtual_classroom#remove_lesson'
  
  # LESSON EDITOR
  get  'lesson_editor/check_conversion'                        => 'lesson_editor#check_conversion'
  post 'lessons/create'                                        => 'lesson_editor#create'
  get  'lessons/:lesson_id/edit'                               => 'lesson_editor#edit',                  :as => :edit_lesson
  get  'lessons/:lesson_id/slides/edit'                        => 'lesson_editor#index',                 :as => :lesson_editor
  post 'lessons/:lesson_id/slides/:slide_id/delete'            => 'lesson_editor#delete_slide',          :as => :delete_slide
  post 'lessons/:lesson_id/slides/:slide_id/kind/:kind/create' => 'lesson_editor#add_slide'
  get  'lessons/:lesson_id/slides/:slide_id/load'              => 'lesson_editor#load_slide'
  post 'lessons/:lesson_id/slides/:slide_id/move/:position'    => 'lesson_editor#change_slide_position', :as => :change_slide_position
  post 'lessons/:lesson_id/slides/:slide_id/update'            => 'lesson_editor#save_slide',            :as => :save_slide
  post 'lessons/:lesson_id/slides/:slide_id/update_and_edit'   => 'lesson_editor#save_slide_and_edit'
  post 'lessons/:lesson_id/slides/:slide_id/update_and_exit'   => 'lesson_editor#save_slide_and_exit'
  put  'lessons/:lesson_id/update'                             => 'lesson_editor#update',                :as => :lesson
  get  'lessons/new'                                           => 'lesson_editor#new',                   :as => :new_lesson
  
  # LESSON EXPORT
  get 'lessons/:lesson_id/archive' => 'lesson_export#archive', :as => :lesson_archive
  get 'lessons/:lesson_id/ebook'   => 'lesson_export#ebook',   :as => :lesson_ebook
  get 'lessons/:lesson_id/scorm'   => 'lesson_export#scorm',   :as => :lesson_scorm
  
  # LESSON VIEWER
  get 'lessons/:lesson_id/view' => 'lesson_viewer#index',    :as => :lesson_viewer
  get 'lessons/view/playlist'   => 'lesson_viewer#playlist', :as => :lesson_viewer_playlist
  
  # LOCATIONS
  get 'admin/locations/:id/find'           => 'admin/users#find_locations'
  get 'admin/purchases/locations/fill'     => 'admin/purchases#fill_locations'
  get 'admin/purchases/locations/:id/find' => 'admin/purchases#find_locations'
  get 'locations/:id/find'                 => 'users#find_locations'
  get 'locations/toggle'                   => 'users#toggle_locations'
  
  # LOGGED USER
  get 'profile'                 => 'users#edit',            :as => :my_profile

app/controllers/faqs_controller.rb
# ### Description
#
# Contains the FAQS, organized into cathegories
#
class FaqsController < ApplicationController
  
  before_filter :initialize_layout
  layout 'faqs'
  
  # Index of all the FAQS
  def index
    @lessons_faqs = t('faqs.lessons.contents')
    @media_elements_faqs = t('faqs.media_elements.contents')
    @virtual_classroom_faqs = t('faqs.virtual_classroom.contents')
    @profile_faqs = t('faqs.profile.contents')
  end
  
  # A FAQ about lessons
  def lessons
    @answer = t('faqs.lessons.contents')[params[:num].to_i - 1]
    if !correct_integer?(params[:num]) || @answer.nil?
      render_not_found
      return
    end
  end
  
  # A FAQ about media elements
  def media_elements
    @answer = t('faqs.media_elements.contents')[params[:num].to_i - 1]
    if !correct_integer?(params[:num]) || @answer.nil?
      render_not_found
      return
    end
  end
  
  # A FAQ about the Virtual Classroom
  def virtual_classroom
    @answer = t('faqs.virtual_classroom.contents')[params[:num].to_i - 1]
    if !correct_integer?(params[:num]) || @answer.nil?
      render_not_found
      return
    end
  end
  
  # A FAQ about user's profile
  def profile
    @answer = t('faqs.profile.contents')[params[:num].to_i - 1]
    if !correct_integer?(params[:num]) || @answer.nil?
      render_not_found
      return
    end
  end
  
  private
  
  # Renders not found page
  def render_not_found
    render text: '404 Not found', :status => :not_found, layout: false
  end
  
end

app/views/faqs/index.html.erb
<div class="gray-description">
  <%= t('faqs.description').html_safe %><br/><br/>
  <%= contact_us_link %>
</div>
<div class="faqs_content">
  <div class="lessons">
    <h2 class="title"><%= t('faqs.lessons.title') %></h2>
    <ul>
      <% @lessons_faqs.each_with_index do |lf, index| %>
        <li><%= link_to lf[0], lessons_faqs_path(index + 1) %></li>
      <% end %>
    </ul>
  </div>
  <div class="media_elements">
    <h2 class="title"><%= t('faqs.media_elements.title') %></h2>
    <ul>
      <% @media_elements_faqs.each_with_index do |mef, index| %>
        <li><%= link_to mef[0], media_elements_faqs_path(index + 1) %></li>
      <% end %>
    </ul>
  </div>
  <div class="virtual_classroom">
    <h2 class="title"><%= t('faqs.virtual_classroom.title') %></h2>
    <ul>
      <% @virtual_classroom_faqs.each_with_index do |vcf, index| %>
        <li><%= link_to vcf[0], virtual_classroom_faqs_path(index + 1) %></li>
      <% end %>
    </ul>
  </div>
  <div class="profile">
    <h2 class="title"><%= t('faqs.profile.title') %></h2>
    <ul>
      <% @profile_faqs.each_with_index do |pf, index| %>
        <li><%= link_to pf[0], profile_faqs_path(index + 1) %></li>
      <% end %>
    </ul>
  </div>
  <br class="clearfloat"/>
</div>

app/views/faqs/lessons.html.erb
<div class="gray-description">
  <%= t('faqs.lessons.description').html_safe %><br/><br/>
  <%= contact_us_link %>
</div>
<div id="lessons_faq">
  <h2 class="title"><%= t('faqs.lessons.title') %></h2>
  <h3 class="answer_title"><%= @answer[0] %></h3>
  <div class="content"><%= @answer[1].html_safe %></div>
  <%= link_to t('faqs.back'), faqs_path, :class => 'backBtn' %>
</div>

app/views/faqs/media_elements.html.erb
<div class="gray-description">
  <%= t('faqs.media_elements.description').html_safe %><br/><br/>
  <%= contact_us_link %>
</div>
<div id="media_elements_faq">
  <h2 class="title"><%= t('faqs.media_elements.title') %></h2>
  <h3 class="answer_title"><%= @answer[0] %></h3>
  <div class="content"><%= @answer[1].html_safe %></div>
  <%= link_to t('faqs.back'), faqs_path, :class => 'backBtn' %>
</div>

app/views/faqs/profile.html.erb
<div class="gray-description">
  <%= t('faqs.profile.description').html_safe %><br/><br/>
  <%= contact_us_link %>
</div>
<div id="profile_faq">
  <h2 class="title"><%= t('faqs.profile.title') %></h2>
  <h3 class="answer_title"><%= @answer[0] %></h3>
  <div class="content"><%= @answer[1].html_safe %></div>
  <%= link_to t('faqs.back'), faqs_path, :class => 'backBtn' %>
</div>

app/views/faqs/virtual_classroom.html.erb
<div class="gray-description">
  <%= t('faqs.virtual_classroom.description').html_safe %><br/><br/>
  <%= contact_us_link %>
</div>
<div id="virtual_classroom_faq">
  <h2 class="title"><%= t('faqs.virtual_classroom.title') %></h2>
  <h3 class="answer_title"><%= @answer[0] %></h3>
  <div class="content"><%= @answer[1].html_safe %></div>
  <%= link_to t('faqs.back'), faqs_path, :class => 'backBtn' %>
</div>