config/routes.rb
Desy::Application.routes.draw do
  
  root :to => 'prelogin#home'
  
  namespace 'admin' do
    root   :to                                       => 'dashboard#index'
    
    # ADMIN DOCUMENTS
    get    'documents'     => 'documents#index',   :as => :documents
    delete 'documents/:id' => 'documents#destroy', :as => :document
    
    # ADMIN LESSONS
    get    'lessons'                    => 'lessons#index',          :as => :lessons
    delete 'lessons/:id'                => 'lessons#destroy',        :as => :lesson
    post   'lessons/:id/publish/toggle' => 'lessons#toggle_publish', :as => :toggle_publish
    
    # ADMIN MEDIA ELEMENTS
    get    'media_elements'                          => 'media_elements#index',              :as => :media_elements
    get    'media_elements/edit'                     => 'media_elements#edit'
    delete 'media_elements/:id'                      => 'media_elements#destroy',            :as => :media_element
    get    'media_elements/:id/load'                 => 'media_elements#load_media_element'
    post   'media_elements/:key/create'              => 'media_elements#create'
    put    'media_elements/:media_element_id/update' => 'media_elements#update'
    get    'media_elements/new'                      => 'media_elements#new'
    post   'media_elements/quick_upload'             => 'media_elements#quick_upload'
    delete 'media_elements/quick_upload/:key/delete' => 'media_elements#quick_upload_delete'
    
    # ADMIN MESSAGES
    post 'messages/filter_users'     => 'messages#filter_users'
    get  'messages/new_notification' => 'messages#new_notification', :as => :messages_new_notification
    get  'messages/reports'          => 'messages#reports'
    
    # ADMIN PERSONIFICATIONS
    delete 'personifications'     => 'personifications#destroy', :as => :personification
    post   'personifications/:id' => 'personifications#create',  :as => :personifications
    
    # ADMIN PURCHASES
    resources :purchases, only: %i(index new create edit update)
    get       'purchases/:id/links/form' => 'purchases#link_form'
    post      'purchases/:id/links/send' => 'purchases#send_link'
    
    # ADMIN REPORTS
    delete 'reports/:id/accept'  => 'reports#accept'
    delete 'reports/:id/decline' => 'reports#decline'
    
    # ADMIN SETTINGS
    get    'settings/locations'                    => 'settings#locations'
    post   'settings/locations/create'             => 'settings#create_location'
    put    'settings/locations/:id/update'         => 'settings#update_location'
    get    'settings/school_levels'                => 'settings#school_levels'
    delete 'settings/school_levels/:id/delete'     => 'settings#delete_school_level'
    post   'settings/school_levels/new'            => 'settings#new_school_level'
    get    'settings/subjects'                     => 'settings#subjects'
    delete 'settings/subjects/:id/delete'          => 'settings#delete_subject'
    post   'settings/subjects/new'                 => 'settings#new_subject'
    get    'settings/tags'                         => 'settings#tags'
    delete 'settings/tags/:id/delete'              => 'settings#delete_tag'
    get    'settings/tags/:id/show/lessons'        => 'settings#lessons_for_tag'
    get    'settings/tags/:id/show/media_elements' => 'settings#media_elements_for_tag'
    
    # ADMIN USERS
    get    'users'                => 'users#index',         :as => :users
    get    'users/get_full_names' => 'users#get_full_names'
    delete 'users/:id'            => 'users#destroy'
    get    'users/:id'            => 'users#show',          :as => :user
    put    'users/:id/activate'   => 'users#activate',      :as => :users_activate
    put    'users/:id/ban'        => 'users#ban',           :as => :users_ban
    post   'users/:id/reconfirm'  => 'users#reconfirm',     :as => :send_again_confirmation
    put    'users/:id/set_status' => 'users#set_status'
    
  end
  
  # AUDIO EDITOR
  get  'audios/:audio_id/edit'   => 'audio_editor#edit'
  post 'audios/cache/empty'      => 'audio_editor#empty_cache',   :as => :audio_editor_empty_cache
  get  'audios/cache/restore'    => 'audio_editor#restore_cache', :as => :audio_editor_restore_cache
  post 'audios/cache/save'       => 'audio_editor#save_cache',    :as => :audio_editor_save_cache
  post 'audios/commit/new'       => 'audio_editor#save'
  post 'audios/commit/overwrite' => 'audio_editor#overwrite'
  get  'audios/new'              => 'audio_editor#new'
  
  # DASHBOARD
  get 'dashboard/lessons'        => 'dashboard#lessons',        :as => :dashboard_lessons
  get 'dashboard/media_elements' => 'dashboard#media_elements', :as => :dashboard_media_elements
  
  # DOCUMENTS
  post   'documents'              => 'documents#create',     :as => :documents
  get    'documents/create/fake'  => 'documents#create_fake'
  delete 'documents/:document_id' => 'documents#destroy'
  post   'documents/:document_id' => 'documents#update',     :as => :document
  
  # FAQS
  get 'faqs'                               => 'faqs#index',             :as => :faqs
  get 'faqs/lessons/:num/answer'           => 'faqs#lessons',           :as => :lessons_faqs
  get 'faqs/media_elements/:num/answer'    => 'faqs#media_elements',    :as => :media_elements_faqs
  get 'faqs/profile/:num/answer'           => 'faqs#profile',           :as => :profile_faqs
  get 'faqs/virtual_classroom/:num/answer' => 'faqs#virtual_classroom', :as => :virtual_classroom_faqs
  
  # GALLERIES
  get 'audios/galleries/audio'               => 'galleries#audio_for_audio_editor' # audio in audio editor
  get 'audios/galleries/audio/new_block'     => 'galleries#audio_for_audio_editor_new_block'
  get 'images/galleries/image'               => 'galleries#image_for_image_editor' # image in image editor
  get 'images/galleries/image/new_block'     => 'galleries#image_for_image_editor_new_block'
  get 'lessons/galleries/audio'              => 'galleries#audio_for_lesson_editor' # audio in lesson editor
  get 'lessons/galleries/audio/new_block'    => 'galleries#audio_for_lesson_editor_new_block'
  get 'lessons/galleries/document'           => 'galleries#document_for_lesson_editor' # documents in lesson editor
  get 'lessons/galleries/document/filter'    => 'galleries#document_for_lesson_editor_filter'
  get 'lessons/galleries/document/new_block' => 'galleries#document_for_lesson_editor_new_block'
  get 'lessons/galleries/image'              => 'galleries#image_for_lesson_editor' # image in lesson editor
  get 'lessons/galleries/image/new_block'    => 'galleries#image_for_lesson_editor_new_block'
  get 'lessons/galleries/video'              => 'galleries#video_for_lesson_editor' # video in lesson editor
  get 'lessons/galleries/video/new_block'    => 'galleries#video_for_lesson_editor_new_block'
  get 'videos/galleries'                     => 'galleries#mixed_for_video_editor' # mixed image + video + text in video editor
  get 'videos/galleries/audio'               => 'galleries#audio_for_video_editor' # audio in video editor
  get 'videos/galleries/audio/new_block'     => 'galleries#audio_for_video_editor_new_block'
  get 'videos/galleries/image/new_block'     => 'galleries#mixed_for_video_editor_image_new_block'
  get 'videos/galleries/video/new_block'     => 'galleries#mixed_for_video_editor_video_new_block'
  
  # GALLERIES QUICK UPLOAD
  post 'lessons/galleries/audios'                     => 'galleries#create_audio'
  post 'lessons/galleries/documents'                  => 'galleries#create_document'
  get  'lessons/galleries/documents/create/fake'      => 'galleries#create_fake_document'
  post 'lessons/galleries/images'                     => 'galleries#create_image'
  get  'lessons/galleries/media_elements/create/fake' => 'galleries#create_fake_media_element'
  post 'lessons/galleries/videos'                     => 'galleries#create_video'
  
  # IMAGE EDITOR
  post 'images/add_text'         => 'image_editor#add_text'
  post 'images/commit/new'       => 'image_editor#save'
  post 'images/commit/overwrite' => 'image_editor#overwrite'
  post 'images/crop'             => 'image_editor#crop'
  get  'images/:image_id/edit'   => 'image_editor#edit'
  post 'images/undo'             => 'image_editor#undo'
  
  # LESSON BUTTONS
  post 'lessons/:lesson_id/add'                      => 'lessons#add'
  post 'lessons/:lesson_id/copy'                     => 'lessons#copy'
  post 'lessons/:lesson_id/destroy'                  => 'lessons#destroy'
  post 'lessons/:lesson_id/dislike'                  => 'lessons#dislike'
  post 'lessons/:lesson_id/dont_notify_modification' => 'lessons#dont_notify_modification'
  post 'lessons/:lesson_id/like'                     => 'lessons#like'
  post 'lessons/:lesson_id/notify_modification'      => 'lessons#notify_modification'
  post 'lessons/:lesson_id/publish'                  => 'lessons#publish'
  post 'lessons/:lesson_id/remove'                   => 'lessons#remove'
  post 'lessons/:lesson_id/unpublish'                => 'lessons#unpublish'
  post 'virtual_classroom/:lesson_id/add_lesson'     => 'virtual_classroom#add_lesson'
  post 'virtual_classroom/:lesson_id/remove_lesson'  => 'virtual_classroom#remove_lesson'
  
  # LESSON EDITOR
  get  'lesson_editor/check_conversion'                        => 'lesson_editor#check_conversion'
  post 'lessons/create'                                        => 'lesson_editor#create'
  get  'lessons/:lesson_id/edit'                               => 'lesson_editor#edit',                  :as => :edit_lesson
  get  'lessons/:lesson_id/slides/edit'                        => 'lesson_editor#index',                 :as => :lesson_editor
  post 'lessons/:lesson_id/slides/:slide_id/delete'            => 'lesson_editor#delete_slide',          :as => :delete_slide
  post 'lessons/:lesson_id/slides/:slide_id/kind/:kind/create' => 'lesson_editor#add_slide'
  get  'lessons/:lesson_id/slides/:slide_id/load'              => 'lesson_editor#load_slide'

app/views/video_editor/_add_component.html.erb
<div id="add_new_video_component" class="newElement">
  <div class="contatore _component_counter" style="opacity:0.3"></div>
  <div class="boxNewMediaElement _new_component_in_video_editor_hover">
    <div class="contentNew _new_component_in_video_editor_button">
      <a class="creaNuovoButton" title="<%= t('titles.video_editor.add_new_component') %>"></a>
    </div>
  </div>
</div>

app/views/video_editor/_audio_track.html.erb
<%
  title = ''
  string_duration = ''
  duration = 0
  style_full = 'display:none'
  style_empty = 'display:block'
  if parameters[:audio_track]
    title = parameters[:audio_track].title
    duration = parameters[:audio_track].min_duration
    string_duration = seconds_to_time(duration)
    style_full = 'display:block'
    style_empty = 'display:none'
  end
%>

<div id="full_audio_track_placeholder_in_video_editor" data-duration="<%= duration %>" class="fltlft" style="<%= style_full %>">
  <div class="audioButton current _show_audio_gallery_in_video_editor"  title="<%= t('titles.video_editor.audio_track.add') %>"></div>
  <div class="titleTrack _title"><%= title %><br/><%= string_duration %></div>
  <div class="fltlft">
    <a class="exitButton _remove" title="<%= t('titles.video_editor.audio_track.remove') %>">&nbsp;</a>
  </div>
</div>

<div id="empty_audio_track_placeholder_in_video_editor" class="fltlft" style="<%= style_empty %>">
  <a class="creaNuovoButton _show_audio_gallery_in_video_editor"></a>
  <p style="padding-top:10px"><%= t('video_editor.audio_track.title') %><br/>
  <span style="color:#3a393a"><%= t('video_editor.audio_track.description') %></span></p>
</div>

app/views/video_editor/_component_menu.html.erb
<div class="_video_editor_component_menu boxMenuMediaElement" style="display:none">
  <a class="cutButton _video_component_cutter_button"  title="<%= t('titles.video_editor.component_menu.cutter') %>"></a>
  <a class="creaNuovoButton _new_component_in_video_editor_button _replace_component"  title="<%= t('titles.video_editor.component_menu.change') %>"></a>
  <a class="closeButton _remove_component_from_video_editor_button"  title="<%= t('titles.video_editor.component_menu.remove') %>"></a>
</div>

app/views/video_editor/_cutters.html.erb
<div id="video_editor_cutters">
  
  <% cont = 1 %>
  <% parameters[:components].each do |c| %>
    <%= render :partial => "video_editor/cutters/#{c[:type]}", :locals => {:component => c, :identifier => cont, :empty => false} %>
    <% cont += 1 %>
  <% end %>
  
</div>

app/views/video_editor/_header.html.erb
<div class="header">
  <div class="contenitore">
    <h1 class="fltlft upper"><%= t("video_editor.label") %></h1>
    <div id="video_editor_title" class="testo fltlft">
      <% if parameters[:initial_video].nil? %>
        <span class="_untitled"><%= t('media_elements.editor.new_untitled') %></span>
      <% else %>
        <span class="_untitled" style="display:none"><%= t('media_elements.editor.new_untitled') %></span>
        <span class="_titled"><%= parameters[:initial_video].title %></span>
      <% end %>
    </div>
    <div class="fltrt"><a class="esciButton _exit_media_element_editor" title="<%= t('titles.exit_without_saving') %>" data-type="video"></a></div>
  </div>
</div>

app/views/video_editor/_preview_container.html.erb
<div id="video_editor_preview_container" class="contentVideo hideMe">
  <% cont = 1 %>
  <% parameters[:components].each do |c| %>
    <%= render :partial => "video_editor/previews/#{c[:type]}", :locals => {:component => c, :identifier => cont, :empty => false, :mute => !parameters[:audio_track].nil?} %>
    <% cont += 1 %>
  <% end %>
  <% if parameters[:audio_track] %>
    <%= render :partial => 'video_editor/previews/audio_track', :locals => {:audio_track => parameters[:audio_track]} %>
  <% end %>
  <div class="_loader" style="padding-top:120px; display:none">
    <%= image_tag 'loading3.gif' %>
  </div>
</div>

app/views/video_editor/_preview_utils.html.erb
<div id="video_editor_preview_slider" style="display:none">
</div>

<div id="video_editor_preview_slider_box_ghost" class="boxGhost"  style="display:none">
</div>

app/views/video_editor/_text_component_editor.html.erb
<%
  
  colors = []
  SETTINGS['colors'].each do |k, v|
    colors[v['pos'] - 1] = k
  end
  
  locals_for_text_thumb = {
    :background_color => 'white',
    :text_color => 'black',
    :content => t('video_editor.components.text.insert')
  }
  
%>

<div id="text_component_preview" class="contentInsertText background_color_white" data-background-color="white" data-text-color="black" data-placeholder="true" data-placeholder-content="<%= t('video_editor.components.text.insert') %>">
  <textarea class="color_black" cols="30" rows="2" maxlength="<%= t('language_parameters.video_editor.length_text_component') %>"><%= t('video_editor.components.text.insert') %></textarea>
</div>

<div class="menuTexts">
  <div class="elementoTime">
    <div class="tempo _duration_selector">
      <p><%= t('video_editor.components.text.time') %></p>
      <input class="numberTime" maxlength="<%= t('language_parameters.video_editor.length_duration') %>"/>
      <p class="lower"><%= t('captions.seconds_shortened') %></p>
    </div>
  </div>
  <div class="elementoGrigio">
    <div class="scegliBgColor _text_component_in_video_editor_background_color_selector">
      <p><%= t('video_editor.components.text.background_color') %></p>
      <% colors.each do |color| %>
        <div class="background_color_<%= color %> _color <%= (color == 'white') ? 'current'.html_safe : '' %>" data-color="<%= color %>"></div>
      <% end %>
    </div>
  </div>
  <div class="elementoGrigio">
    <div class="scegliTxtColor _text_component_in_video_editor_text_color_selector">
      <p><%= t('video_editor.components.text.color') %></p>
      <% colors.each do |color| %>
        <div class="background_color_<%= color %> _color <%= (color == 'black') ? 'current'.html_safe : '' %>" data-color="<%= color %>"></div>
      <% end %>
    </div>
  </div>
  <div class="bottoniVerdi fltrt"><a id="insert_text_component_in_video_editor" class="upper"><%= t('video_editor.components.text.done') %></a></div>
</div>

<div class="_temporary" style="display:none">
  <%= render :partial => 'video_editor/components/thumbs/text', :locals => locals_for_text_thumb %>
</div>

app/views/video_editor/_timeline.html.erb
<div class="scrollVerde" style="position:relative">
  <div id="video_editor_box_ghost" class="boxGhost" style="display:none;"></div>
  <div class="scroll-pane horizontal-only" id="media_elements_list_in_video_editor">
    <div id="video_editor_timeline" class="scrollGatto" style="width:<%= (186 * parameters[:components].length) + 160 %>px">
      
      <% cont = 1 %>
      <% parameters[:components].each do |p| %>
        <% p[:last] = (cont == parameters[:components].length) %>
        <%= render :partial => "video_editor/components/#{p[:type]}", :locals => {:component => p, :position => cont, :empty => false} %>
        <% cont += 1 %>
      <% end %>
      
      <%= render :partial => 'video_editor/add_component', :locals => {:parameters => @parameters, :position => cont} %>
      
    </div>
  </div>
</div>

app/views/video_editor/edit.html.erb
<%= render :partial => 'video_editor/header', :locals => {:parameters => @parameters} %>

<div id="video_editor" class="mediaEditorVideoContainer">
  
  <%= render :partial => 'video_editor/preview_container', :locals => {:parameters => @parameters} %>
  
  <div class="global-data hideMe">
    
    <% if @parameters[:components].any? %>
      <div id="video_editor_global_preview" class="bottoniVerdi _enabled" data-current-component="0" data-current-time="0" data-in-use="false" data-arrows="true">
        <a class="upper"><%= t('video_editor.preview.label') %></a>
      </div>
    <% else %>
      <div id="video_editor_global_preview" class="bottoniVerdi" data-current-component="0" data-current-time="0" data-in-use="false" data-arrows="true">
        <a class="upper disabled"><%= t('video_editor.preview.label') %></a>
      </div>
    <% end %>
    
    <div id="video_editor_global_preview_pause" class="bottoniVerdi" style="display:none">
      <a class="upper"><%= t('video_editor.preview.pause') %></a>
    </div>
    <div id="video_editor_global_preview_play" class="bottoniVerdi" style="display:none" data-temporarily-disabled="false">
      <a class="upper"><%= t('video_editor.preview.play') %></a>
    </div>
    <p class="capitalize" style="color:#43a848"><%= t('video_editor.total_length') %>:</p>
    <p>
      <span id="visual_video_editor_total_length"><%= seconds_to_time(@total_length) %></span><br/>
      <span id="visual_video_editor_current_time" style="visibility:hidden; color:#787575"><%= seconds_to_time(0) %></span>
    </p>
  </div>
  
  <%= form_tag video_editor_save_cache_path, :id => 'video_editor_form', :remote => true, :autocomplete => 'off' do %>
    <%= render :partial => 'media_elements/info_form_in_editor/new', :locals => {:type => MediaElement::VIDEO_TYPE.downcase, :edited => @edited_video} %>
    <% if @parameters[:initial_video] %>
      <%= render :partial => 'media_elements/info_form_in_editor/edit', :locals => {:media_element => @parameters[:initial_video]} %>
    <% end %>
    <div class="mediaEditorListaElementi hideMe">
      <% if @parameters[:initial_video] %>
        <%= hidden_field_tag 'initial_video_id', @parameters[:initial_video].id, :id => 'initial_video_in_video_editor_input' %>
      <% end %>
      <%= hidden_field_tag 'audio_id', (@parameters[:audio_track].nil? ? '' : @parameters[:audio_track].id), :id => 'audio_track_in_video_editor_input' %>
      <a id="video_editor_preview_go_to_left_component" style="display:none"></a>
      <%= render :partial => 'timeline', :locals => {:parameters => @parameters} %>
      <a id="video_editor_preview_go_to_right_component" style="display:none"></a>
      <div class="addAudioandSave _video_editor_bottom_bar">
        <%= render :partial => 'audio_track', :locals => {:parameters => @parameters} %>
        <div class="fltrt">
          <div class="fltrt">
            <a class="_commit_media_element_editor nextButton <%= @parameters[:initial_video].nil? ? '' : '_with_choice'.html_safe %>" title="<%= t('titles.video_editor.commit') %>" style="visibility:<%= @parameters[:components].any? ? 'visible'.html_safe : 'hidden'.html_safe %>" data-type="video">
            </a>
            <a id="exit_video_editor_preview" class="closeButton" style="display:none" title="<%= t('titles.video_editor.close_preview') %>"></a>
          </div>
        </div>
      </div>
      <%= render :partial => 'cutters', :locals => {:parameters => @parameters} %>
      <%= render :partial => 'preview_utils' %>
    </div>
  <% end %>
  
</div>


<div id="empty_video_component_for_video_editor" style="display:none">
  <%= render :partial => "video_editor/components/video", :locals => {:component => {}, :position => 1, :empty => true} %>
</div>

<div id="empty_image_component_for_video_editor" style="display:none">
  <%= render :partial => "video_editor/components/image", :locals => {:component => {}, :position => 1, :empty => true} %>
</div>

<div id="empty_text_component_for_video_editor" style="display:none">
  <%= render :partial => "video_editor/components/text", :locals => {:component => {}, :position => 1, :empty => true} %>
</div>


<div id="empty_video_preview_for_video_editor" style="display:none">
  <%= render :partial => 'video_editor/previews/video', :locals => {:component => {}, :identifier => 1, :empty => true, :mute => false} %>
</div>

<div id="empty_image_preview_for_video_editor" style="display:none">
  <%= render :partial => 'video_editor/previews/image', :locals => {:component => {}, :identifier => 1, :empty => true} %>
</div>

<div id="empty_text_preview_for_video_editor" style="display:none">
  <%= render :partial => 'video_editor/previews/text', :locals => {:component => {}, :identifier => 1, :empty => true} %>
</div>

<div id="empty_audio_track_preview_for_video_editor" style="display:none">
  <%= render :partial => 'video_editor/previews/audio_track', :locals => {:audio_track => nil} %>
</div>


<div id="empty_video_cutter_for_video_editor" style="display:none">
  <%= render :partial => 'video_editor/cutters/video', :locals => {:component => {}, :identifier => 1, :empty => true} %>
</div>

<div id="empty_image_cutter_for_video_editor" style="display:none">
  <%= render :partial => 'video_editor/cutters/image', :locals => {:component => {}, :identifier => 1, :empty => true} %>
</div>

<div id="empty_text_cutter_for_video_editor" style="display:none">
  <%= render :partial => 'video_editor/cutters/text', :locals => {:component => {}, :identifier => 1, :empty => true} %>
</div>


<div id="video_editor_mixed_gallery_container" class="mediaElementGalleryContainer" style="display:none" data-loaded="false" data-video-page="0" data-video-tot-pages="0" data-image-page="0" data-image-tot-pages="0"></div>

<div id="video_editor_audio_gallery_container" class="mediaElementGalleryContainer" style="display:none" data-loaded="false" data-page="0" data-tot-pages="0"></div>

<div id="info_container" data-last-component-id="<%= @parameters[:components].count %>" data-current-component="" data-replacing-component="false" data-total-length="<%= @total_length %>" data-save-cache="false" data-cache-enabled-first-time="true" data-forced-kevin-luck-style="" data-used-in-private-lessons="<%= @used_in_private_lessons %>" style="display:none"></div>


<script>
  $(document).ready(function() {
    <% if @cache.nil? %>
      setTimeout(function() {
        if($('#info_container').data('cache-enabled-first-time')) {
          startCacheLoop();
        }
      }, $('#popup_parameters_container').data('cache-time'));
    <% else %>
      showRestoreCacheMediaElementEditorPopUp(function() {
        window.location.href = '/videos/cache/restore'
      }, function() {
        closePopUp('dialog-restore-cache-media-element-editor');
        unbindLoader();
        $.ajax({
          type: 'post',
          url: '/videos/cache/empty',
          success: function() {
            setTimeout(function() {
              if($('#info_container').data('cache-enabled-first-time')) {
                startCacheLoop();
              }
            }, $('#popup_parameters_container').data('cache-time'));
          }
        }).always(bindLoader);
      });
    <% end %>
  });
</script>

app/views/video_editor/not_available.html.erb
<div class="header">
  <div class="contenitore" style="width: 960px; margin: 0 auto; display: inline-block;" >
    <div class="fltrt"><a href="javascript:history.back();" class="esciButton" title="<%= t('titles.exit') %>"></a></div>
  </div>
</div>
<div class="mediaSelectEditorButtonContainer">
  <div class="contentTitle">
    <h1><%= t('video_editor.not_available.title') %></h1>
    <h2><%= t('video_editor.not_available.description') %></h2>
  </div>
</div>