config/routes.rb
Desy::Application.routes.draw do
  
  root :to => 'prelogin#home'
  
  namespace 'admin' do
    root   :to                                       => 'dashboard#index'
    
    # ADMIN DOCUMENTS
    get    'documents'     => 'documents#index',   :as => :documents
    delete 'documents/:id' => 'documents#destroy', :as => :document
    
    # ADMIN LESSONS
    get    'lessons'                    => 'lessons#index',          :as => :lessons
    delete 'lessons/:id'                => 'lessons#destroy',        :as => :lesson
    post   'lessons/:id/publish/toggle' => 'lessons#toggle_publish', :as => :toggle_publish
    
    # ADMIN MEDIA ELEMENTS
    get    'media_elements'                          => 'media_elements#index',              :as => :media_elements
    get    'media_elements/edit'                     => 'media_elements#edit'
    delete 'media_elements/:id'                      => 'media_elements#destroy',            :as => :media_element
    get    'media_elements/:id/load'                 => 'media_elements#load_media_element'
    post   'media_elements/:key/create'              => 'media_elements#create'
    put    'media_elements/:media_element_id/update' => 'media_elements#update'
    get    'media_elements/new'                      => 'media_elements#new'
    post   'media_elements/quick_upload'             => 'media_elements#quick_upload'
    delete 'media_elements/quick_upload/:key/delete' => 'media_elements#quick_upload_delete'
    
    # ADMIN MESSAGES
    post 'messages/filter_users'     => 'messages#filter_users'
    get  'messages/new_notification' => 'messages#new_notification', :as => :messages_new_notification
    get  'messages/reports'          => 'messages#reports'
    
    # ADMIN PERSONIFICATIONS
    delete 'personifications'     => 'personifications#destroy', :as => :personification
    post   'personifications/:id' => 'personifications#create',  :as => :personifications
    
    # ADMIN PURCHASES
    resources :purchases, only: %i(index new create edit update)
    get       'purchases/:id/links/form' => 'purchases#link_form'
    post      'purchases/:id/links/send' => 'purchases#send_link'
    
    # ADMIN REPORTS
    delete 'reports/:id/accept'  => 'reports#accept'
    delete 'reports/:id/decline' => 'reports#decline'
    
    # ADMIN SETTINGS
    get    'settings/locations'                    => 'settings#locations'
    post   'settings/locations/create'             => 'settings#create_location'
    put    'settings/locations/:id/update'         => 'settings#update_location'
    get    'settings/school_levels'                => 'settings#school_levels'
    delete 'settings/school_levels/:id/delete'     => 'settings#delete_school_level'
    post   'settings/school_levels/new'            => 'settings#new_school_level'
    get    'settings/subjects'                     => 'settings#subjects'
    delete 'settings/subjects/:id/delete'          => 'settings#delete_subject'
    post   'settings/subjects/new'                 => 'settings#new_subject'
    get    'settings/tags'                         => 'settings#tags'
    delete 'settings/tags/:id/delete'              => 'settings#delete_tag'
    get    'settings/tags/:id/show/lessons'        => 'settings#lessons_for_tag'
    get    'settings/tags/:id/show/media_elements' => 'settings#media_elements_for_tag'
    
    # ADMIN USERS
    get    'users'                => 'users#index',         :as => :users
    get    'users/get_full_names' => 'users#get_full_names'
    delete 'users/:id'            => 'users#destroy'
    get    'users/:id'            => 'users#show',          :as => :user
    put    'users/:id/activate'   => 'users#activate',      :as => :users_activate
    put    'users/:id/ban'        => 'users#ban',           :as => :users_ban
    post   'users/:id/reconfirm'  => 'users#reconfirm',     :as => :send_again_confirmation
    put    'users/:id/set_status' => 'users#set_status'
    
  end
  
  # AUDIO EDITOR
  get  'audios/:audio_id/edit'   => 'audio_editor#edit'
  post 'audios/cache/empty'      => 'audio_editor#empty_cache',   :as => :audio_editor_empty_cache
  get  'audios/cache/restore'    => 'audio_editor#restore_cache', :as => :audio_editor_restore_cache
  post 'audios/cache/save'       => 'audio_editor#save_cache',    :as => :audio_editor_save_cache
  post 'audios/commit/new'       => 'audio_editor#save'
  post 'audios/commit/overwrite' => 'audio_editor#overwrite'
  get  'audios/new'              => 'audio_editor#new'
  
  # DASHBOARD
  get 'dashboard/lessons'        => 'dashboard#lessons',        :as => :dashboard_lessons
  get 'dashboard/media_elements' => 'dashboard#media_elements', :as => :dashboard_media_elements
  
  # DOCUMENTS
  post   'documents'              => 'documents#create',     :as => :documents
  get    'documents/create/fake'  => 'documents#create_fake'
  delete 'documents/:document_id' => 'documents#destroy'
  post   'documents/:document_id' => 'documents#update',     :as => :document
  
  # FAQS
  get 'faqs'                               => 'faqs#index',             :as => :faqs
  get 'faqs/lessons/:num/answer'           => 'faqs#lessons',           :as => :lessons_faqs
  get 'faqs/media_elements/:num/answer'    => 'faqs#media_elements',    :as => :media_elements_faqs
  get 'faqs/profile/:num/answer'           => 'faqs#profile',           :as => :profile_faqs
  get 'faqs/virtual_classroom/:num/answer' => 'faqs#virtual_classroom', :as => :virtual_classroom_faqs
  
  # GALLERIES
  get 'audios/galleries/audio'               => 'galleries#audio_for_audio_editor' # audio in audio editor
  get 'audios/galleries/audio/new_block'     => 'galleries#audio_for_audio_editor_new_block'
  get 'images/galleries/image'               => 'galleries#image_for_image_editor' # image in image editor
  get 'images/galleries/image/new_block'     => 'galleries#image_for_image_editor_new_block'
  get 'lessons/galleries/audio'              => 'galleries#audio_for_lesson_editor' # audio in lesson editor
  get 'lessons/galleries/audio/new_block'    => 'galleries#audio_for_lesson_editor_new_block'
  get 'lessons/galleries/document'           => 'galleries#document_for_lesson_editor' # documents in lesson editor
  get 'lessons/galleries/document/filter'    => 'galleries#document_for_lesson_editor_filter'
  get 'lessons/galleries/document/new_block' => 'galleries#document_for_lesson_editor_new_block'
  get 'lessons/galleries/image'              => 'galleries#image_for_lesson_editor' # image in lesson editor
  get 'lessons/galleries/image/new_block'    => 'galleries#image_for_lesson_editor_new_block'
  get 'lessons/galleries/video'              => 'galleries#video_for_lesson_editor' # video in lesson editor
  get 'lessons/galleries/video/new_block'    => 'galleries#video_for_lesson_editor_new_block'
  get 'videos/galleries'                     => 'galleries#mixed_for_video_editor' # mixed image + video + text in video editor
  get 'videos/galleries/audio'               => 'galleries#audio_for_video_editor' # audio in video editor
  get 'videos/galleries/audio/new_block'     => 'galleries#audio_for_video_editor_new_block'
  get 'videos/galleries/image/new_block'     => 'galleries#mixed_for_video_editor_image_new_block'
  get 'videos/galleries/video/new_block'     => 'galleries#mixed_for_video_editor_video_new_block'
  
  # GALLERIES QUICK UPLOAD
  post 'lessons/galleries/audios'                     => 'galleries#create_audio'
  post 'lessons/galleries/documents'                  => 'galleries#create_document'
  get  'lessons/galleries/documents/create/fake'      => 'galleries#create_fake_document'
  post 'lessons/galleries/images'                     => 'galleries#create_image'
  get  'lessons/galleries/media_elements/create/fake' => 'galleries#create_fake_media_element'
  post 'lessons/galleries/videos'                     => 'galleries#create_video'
  
  # IMAGE EDITOR
  post 'images/add_text'         => 'image_editor#add_text'
  post 'images/commit/new'       => 'image_editor#save'
  post 'images/commit/overwrite' => 'image_editor#overwrite'
  post 'images/crop'             => 'image_editor#crop'
  get  'images/:image_id/edit'   => 'image_editor#edit'
  post 'images/undo'             => 'image_editor#undo'
  
  # LESSON BUTTONS
  post 'lessons/:lesson_id/add'                      => 'lessons#add'
  post 'lessons/:lesson_id/copy'                     => 'lessons#copy'
  post 'lessons/:lesson_id/destroy'                  => 'lessons#destroy'
  post 'lessons/:lesson_id/dislike'                  => 'lessons#dislike'
  post 'lessons/:lesson_id/dont_notify_modification' => 'lessons#dont_notify_modification'
  post 'lessons/:lesson_id/like'                     => 'lessons#like'
  post 'lessons/:lesson_id/notify_modification'      => 'lessons#notify_modification'
  post 'lessons/:lesson_id/publish'                  => 'lessons#publish'
  post 'lessons/:lesson_id/remove'                   => 'lessons#remove'
  post 'lessons/:lesson_id/unpublish'                => 'lessons#unpublish'
  post 'virtual_classroom/:lesson_id/add_lesson'     => 'virtual_classroom#add_lesson'
  post 'virtual_classroom/:lesson_id/remove_lesson'  => 'virtual_classroom#remove_lesson'
  
  # LESSON EDITOR
  get  'lesson_editor/check_conversion'                        => 'lesson_editor#check_conversion'
  post 'lessons/create'                                        => 'lesson_editor#create'
  get  'lessons/:lesson_id/edit'                               => 'lesson_editor#edit',                  :as => :edit_lesson
  get  'lessons/:lesson_id/slides/edit'                        => 'lesson_editor#index',                 :as => :lesson_editor
  post 'lessons/:lesson_id/slides/:slide_id/delete'            => 'lesson_editor#delete_slide',          :as => :delete_slide
  post 'lessons/:lesson_id/slides/:slide_id/kind/:kind/create' => 'lesson_editor#add_slide'
  get  'lessons/:lesson_id/slides/:slide_id/load'              => 'lesson_editor#load_slide'

app/controllers/admin/documents_controller.rb
# ### Description
#
# Controller of documents in the administration section. See AdminController.
#
# ### Models used
#
# * Document
# * AdminSearchForm
#
class Admin::DocumentsController < AdminController
  
  layout 'admin'
  
  # ### Description
  #
  # Main page of documents in the admin. If params[:search] is present, it is used AdminSearchForm to perform the requested search.
  #
  # ### Mode
  #
  # Html
  #
  # ### Specific filters
  #
  # * ApplicationController#admin_authenticate
  #
  def index
    documents = AdminSearchForm.search_documents((params[:search] ? params[:search] : {:ordering => 0, :desc => 'true'}))
    @documents = documents.page(params[:page])
    @locations = [Location.roots.order(:name)]
    if params[:search]
      location = Location.get_from_chain_params params[:search]
      @locations = location.select_without_selected if location
    end
  end
  
  # ### Description
  #
  # Destroys a document, sending notifications if it's used in somebody's lessons.
  #
  # ### Mode
  #
  # Html
  #
  # ### Specific filters
  #
  # * ApplicationController#admin_authenticate
  #
  def destroy
    @document = Document.find(params[:id])
    @document.destroy_with_notifications
    redirect_to params[:back_url]
  end
  
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  
  # Number of documents for each page
  FOR_PAGE = 8
  
  before_filter :initialize_document, :only => [:destroy, :update]
  before_filter :initialize_layout, :initialize_paginator, :only => :index
  
  # ### Description
  #
  # Main page of the section 'documents'. When it's called via ajax it's because of the application of filters, paginations, or after an operation that changed the number of items in the page.
  #
  # ### Mode
  #
  # Html + Ajax
  #
  # ### Specific filters
  #
  # * ApplicationController#initialize_layout
  # * DocumentsController#initialize_paginator
  #
  def index
    get_own_documents
    if @page > @pages_amount && @pages_amount != 0
      @page = @pages_amount
      get_own_documents
    end
    render_js_or_html_index
  end
  
  # ### Description
  #
  # Deletes definitively a document.
  #
  # ### Mode
  #
  # Json
  #
  # ### Specific filters
  #
  # * ApplicationController#initialize_document
  #
  def destroy
    if @ok
      if !@document.destroy_with_notifications
        @ok = false
        @error = I18n.t('activerecord.errors.models.document.problem_destroying')
      end
    else
      @error = I18n.t('activerecord.errors.models.document.problem_destroying')
    end
    render :json => {:ok => @ok, :msg => @error}
  end
  
  # ### Description
  #
  # Updates the general information of the document (title and description)
  #
  # ### Mode
  #
  # Ajax
  #
  # ### Specific filters
  #
  # * ApplicationController#initialize_document
  #
  def update
    if @ok
      @word = params[:word].blank? ? nil : params[:word]
      @document.title = params[:title]
      @document.description = params[:description]
      if !@document.save
        @errors = convert_document_error_messages @document.errors
      end
    end
  end
  
  # ### Description
  #
  # This action checks for errors without setting the attachment on the new document
  #
  # ### Mode
  #
  # Js
  #
  def create_fake
    record = Document.new
    record.title = params[:title_placeholder] != '0' ? '' : params[:title]
    record.description = params[:description_placeholder] != '0' ? '' : params[:description]
    record.user_id = current_user.id
    record.valid?
    @errors = convert_document_error_messages record.errors
    @errors[:media] = t('documents.upload_form.attachment_too_large').downcase
  end
  
  # ### Description
  #
  # Action that calls the uploader and creates the new document
  #
  # ### Mode
  #
  # Html
  #
  def create
    record = Document.new :attachment => params[:media]
    record.title = params[:title_placeholder] != '0' ? '' : params[:title]
    record.description = params[:description_placeholder] != '0' ? '' : params[:description]
    record.user_id = current_user.id
    if !record.save
      if record.errors.added? :attachment, :too_large
        return render :file => Rails.root.join('public/413.html'), :layout => false, :status => 413
      end
      @errors = convert_document_error_messages record.errors
    end
    render :layout => false
  end
  
  private
  
  # Gets the documents using User#own_documents
  def get_own_documents
    current_user_own_documents = current_user.own_documents(@page, @for_page, @order, @word)
    @documents = current_user_own_documents[:records]
    @pages_amount = current_user_own_documents[:pages_amount]
  end
  
  # Initializes pagination parameters and filters
  def initialize_paginator
    @page = correct_integer?(params[:page]) ? params[:page].to_i : 1
    @for_page = FOR_PAGE
    @order = SearchOrders::DOCUMENTS_SET.include?(params[:order]) ? params[:order] : SearchOrders::CREATED_AT
    @word = params[:word].blank? ? nil : params[:word]
  end
  
end

app/views/documents/_empty.html.erb
<div class="empty-situation-container">
  <a class="openLoader" data-type="document">
    <div class="plus"></div>
    <div class="prompts">
      <div class="reason">
        <%= t('documents.empty') %>
      </div>
      <div class="big-prompt">
        <%= t('documents.upload_now') %>
      </div>
    </div>
  </a>
</div>

app/views/documents/_empty_word.html.erb
<div class="emptyFilter">
  <h1><%= t('documents.empty_word', :word => word) %></h1>
</div>

app/views/documents/_my_documents.html.erb
<div id="my_documents">
  <% if documents.empty? %>
    <% if word.nil? %>
      <%= render :partial => 'documents/empty' %>
    <% else %>
      <%= render :partial => 'documents/empty_word', :locals => {:word => word} %>
    <% end %>
  <% else %>
    <% documents.each_with_index do |d, index| %>
      <% forced_margin = (index == documents.length - 1) ? (@for_page - documents.length) : nil %>
      <%= render :partial => 'documents/view_single_compact', :locals => {:document => d, :word => word, :used_in_your_lessons => (d.instances.to_i != 0), :forced_margin => forced_margin} %>
    <% end %>
  <% end %>
</div>

app/views/documents/_new_form_popup.html.erb
<%
  title_max = t('documents.title_placeholder', :num => t('language_parameters.document.length_title').to_s).downcase
  description_max = t('documents.description_placeholder', :num => t('language_parameters.document.length_description').to_s).downcase
%>

<div id="load-document" class="globalLoader document" style="display:none" data-placeholder-title="<%= title_max %>" data-placeholder-description="<%= description_max %>" data-placeholder-media="<%= t('documents.upload_form.attachment_placeholder').downcase %>" data-loader-can-move="true" data-loader-with-errors="false" data-loader-position-stop="0" data-bar-width="760" data-bar-height="440" data-bar-padding="40" data-fake-url="/documents/create/fake">
  <%= form_tag documents_path, :method => :post, :id => 'new_document', :class => 'form-selector-class', :multipart => true, :autocomplete => 'off' do %>
    <div class="part1">
      <div class="attachment">
        <label>
          <span>
            <input type="file" class="file" name="media"/>
          </span>
        </label>
        <input class="media" disabled="disabled" value=""/>
      </div>
      <div class="title_and_subtitle">
        <h1>
          <%= t('documents.upload_form.title') %>
        </h1>
        <p>
          <%= t('documents.upload_form.description') %>
        </p>
      </div>
    </div>
    <div class="part2">
      <div class="title_and_description">
        <input class="title" type="text" value="" name="title"/>
        <input class="title_placeholder" type="hidden" value="" name="title_placeholder"/>
        <textarea class="description" name="description"></textarea>
        <input class="description_placeholder" type="hidden" value="" name="description_placeholder"/>
      </div>
    </div>
    <div class="part3">
      <a class="submit"><%= t('documents.upload_form.done').downcase %></a>
      <a class="close"><%= t('documents.upload_form.cancel').downcase %></a>
    </div>
    <div class="loading-square loading-square-1"></div>
    <div class="loading-square loading-square-2"></div>
    <div class="loading-square loading-square-3"></div>
    <div class="loading-square loading-square-4"></div>
    <div class="loading-square loading-square-5"></div>
    <div class="loading-square-bis loading-square-bis-1"></div>
    <div class="loading-square-bis loading-square-bis-2"></div>
    <div class="loading-square-bis loading-square-bis-3"></div>
    <div class="loading-square-bis loading-square-bis-4"></div>
    <div class="errors_layer description" data-focus-selector=".part2 .description" data-form-error-selector=".part2 .description" data-focus-action="focus"></div>
    <div class="errors_layer media" data-form-error-selector=".part1 .attachment .media"></div>
    <div class="errors_layer title" data-focus-selector=".part2 .title" data-form-error-selector=".part2 .title" data-focus-action="focus"></div>
  <% end %>
  <div class="full_folder">
    <p class="msge"></p>
    <a class="back_to_gallery"><%= t('forms.error_captions.document_folder_full_button_from_dashboard') %></a>
  </div>
</div>

app/views/documents/_popup.html.erb
<div id="dialog-document-<%= document.id %>" class="dialogDocument ornitorinco echidna pippofranco" style="display:none">
  <div class="wrapper">
    <div class="preview">
      <div class="content">
        <%= image_tag document.icon_url %>
      </div>
      <div class="description">
        <h2><%= t('documents.caption') %></h2>
        <h3><%= document.title %></h3>
        <p><%= document.description %></p>
        <a href="<%= document.url %>"><%= t('documents.download') %></a>
        <h4><%= t('documents.human_size', :number => document.human_size).downcase %></h4>
        <h4><%= t('documents.format', :type => document.extension).downcase %></h4>
      </div>
    </div>
    <div class="change-info" style="display:none" data-title="<%= document.title %>" data-description="<%= document.description %>">
      <%= form_tag document_path(document.id), :remote => true, :class => 'form-selector-class', :autocomplete => 'off' do %>
        <div class="part1">
          <div class="attachment">
            <div class="icon"></div>
          </div>
          <div class="title_and_subtitle">
            <h1>
              <%= t('forms.change_info_document.title') %>
            </h1>
            <p>
              <%= t('forms.change_info_document.description') %>
            </p>
          </div>
        </div>
        <div class="part2">
          <div class="title_and_description">
            <input type="hidden" value="" name="word" class="hidden_word">
            <input class="title" type="text" value="<%= document.title %>" name="title"/>
            <textarea class="description" name="description"><%= document.description %></textarea>
          </div>
        </div>
        <div class="part3">
          <a class="submit"><%= t('forms.change_info_document.done').downcase %></a>
          <a class="close"><%= t('forms.change_info_document.cancel').downcase %></a>
        </div>
        <div class="errors_layer description" data-focus-selector=".part2 .description" data-form-error-selector=".part2 .description" data-focus-action="focus"></div>
        <div class="errors_layer title" data-focus-selector=".part2 .title" data-form-error-selector=".part2 .title" data-focus-action="focus"></div>
      <% end %>
    </div>
  </div>
  <div class="menu">
    <div class="on-left">
      <a class="change-info" title="<%= t('titles.buttons.documents.change_info') %>"></a>
    </div>
    <div class="on-right">
      <a class="close" title="<%= t('titles.close') %>"></a>
    </div>
  </div>
</div>

app/views/documents/_view_single_compact.html.erb
<%
  forced_margin ||= nil
  if forced_margin.nil?
    forced_margin = ''
  else
    forced_margin = "style=\"margin-bottom:#{(71 * forced_margin)}px\"".html_safe
  end
  my_title = html_escape document.title
  my_title.gsub! /(#{Regexp.quote word})/i, '<b><u>\1</u></b>' if word.present?
  my_title = my_title.html_safe
%>

<div id="document_<%= document.id %>" class="boxViewSingleDocument" <%= forced_margin %>>
  <div class="contentInterno">
    <div class="documentsIcon">
      <%= image_tag document.icon_url, :class=> 'fltlft', :title => document.icon_title %>
      <h3><%= my_title %></h3>
    </div>
     <p class="upper"><%= document.size_and_extension %></p>
    <div class="menuController buttons">
      <a title="<%= t('titles.buttons.documents.preview') %>" data-document-id="<%= document.id %>" class="preview"></a>
      <a title="<%= t('titles.buttons.documents.destroy') %>" data-used-in-your-lessons="<%= used_in_your_lessons %>" data-document-id="<%= document.id %>" class="destroy"></a>
    </div>
  </div>
  <%= render :partial => 'documents/popup', :locals => {:document => document} %>
</div>

app/views/documents/create.html.erb
<script>
  window.onload = function() {
    top.uploadDone('#load-document', <%= @errors ? @errors.to_json.html_safe : 'undefined' %>, function() {
       top.window.location = '/documents';
    });
  }
</script>

app/views/documents/create_fake.js.erb
uploadDone('#load-document', <%= @errors.to_json.html_safe %>);

app/views/documents/index.html.erb
<%= render :partial => 'documents/new_form_popup' %>
<%= render :partial => 'shared/upload_target' %>
<div class="gray-bar">
  <a id="upload_document" class="navlist-item b-document openLoader lower" data-type="document"><%= t('documents.upload') %></a>
</div>
<br class="clearfloat"/>
<div class="griglia-contenuti">
  <div class="documents-content fixed-compact-height">
    <div id="documents_title_bar" class="title-bar">
      <h1 class="lower"><%= t('captions.documents') %></h1>
      <div class="sort">
        <h2><%= t('captions.sort') %></h2>
        <select id="order_documents">
          <% SearchOrders::DOCUMENTS_SET.each do |so| %>
            <option value="<%= so %>" <%= (@order == so) ? "selected=\"selected\"".html_safe : '' %>><%= t("orders.#{so}") %></option>
          <% end %>
        </select>
      </div>
      <div class="filter">
        <form id="search_documents" class="search-form" method="get" action="/documents" data-remote="true" autocomplete="off">
          <h2><%= t('documents.search') %></h2>
          <input type="text" name="word" value="" class="text lower _word_input" data-letters="0"/>
          <%= image_tag 'cerca_documenti.gif', :class => '_loader', :style => 'display:none' %>
          <%= hidden_field_tag 'order', '', :id => 'search_documents_hidden_order' %>
        </form>
      </div>
    </div>
    <%= render :partial => 'documents/my_documents', :locals => {:documents => @documents, :word => @word} %>
    <div id="info_container" style="display:none" data-currenturl="<%= request.url %>"></div>
    <br class="clearfloat"/>
    <% if @documents.present? %>
      <%= render :partial => 'shared/pagination', :locals => {:page => @page, :pages_amount => @pages_amount} %>
    <% end %>
  </div>
</div>

app/views/documents/index.js.erb
removeCompletelyAllDocumentPopups();
<% if @delete_item.blank? %>
  $('#my_documents').hide('fade', {}, 500, function() {
    $('#my_documents').replaceWith("<%= j(render(:partial => 'documents/my_documents', :locals => {:documents => @documents, :word => @word})) %>");
    <% if @documents.any? %>
      $('#general_pagination').replaceWith("<%= j(render(:partial => 'shared/pagination', :locals => {:page => @page, :pages_amount => @pages_amount})) %>");
    <% else %>
      $('#general_pagination').html('');
    <% end %>
  });
<% else %>
  var to_delete = $('#<%= @delete_item %>');
  to_delete.hide('fade', {}, 500, function() {
    $('#my_documents').replaceWith("<%= j(render(:partial => 'documents/my_documents', :locals => {:documents => @documents, :word => @word})) %>");
    <% if @documents.any? %>
      $('#general_pagination').replaceWith("<%= j(render(:partial => 'shared/pagination', :locals => {:page => @page, :pages_amount => @pages_amount})) %>");
    <% else %>
      $('#general_pagination').html('');
    <% end %>
  });
<% end %>

$('#info_container').data('currenturl', <%= manipulate_url(remove_query_param: ["delete_item"], page: @page).to_json.html_safe %>);

app/views/documents/update.js.erb
<% if @ok %>
  <% if @errors %>
    showFormErrors($('#dialog-document-<%= @document.id %>'), <%= @errors.to_json.html_safe %>);
  <% else %>
    closePopUp('dialog-document-<%= @document_id %>');
    removeCompletelyDocumentPopup(<%= @document_id %>);
    $('#document_<%= @document_id %>').replaceWith('<%= j render(:partial => "documents/view_single_compact", :locals => {:document => @document, :word => @word, :used_in_your_lessons => @document.used_in_your_lessons?}) %>');
  <% end %>
<% end %>